# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          name: Save cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: yarn run lint && yarn run test:unit
          command: |
            yarn run lint
            yarn run test:unit

  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # ftallback to using the latest cache if no exact mach is found
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: yarn install
        command: |
          yarn install
          yarn run build

      - persist_to_workspace:
          root: docs
          paths: .

workflows:
  version: 2
  develop:
    jobs:
      - install:
          filters:
            branches:
              only: dev
      - test:
          filters:
            branches:
              only: dev
          requires:
            - install
      - build:
          filters:
            branches:
              only: dev
          requires:
            - install
            - test
