version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: npm install
          command: npm install
      - save_cache:
          name: Save cache
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules/

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: npm run eslint and npm run test:unit
          command: |
            npm run lint
            npm run test:unit

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: npm run build
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: docs
          paths: .
  deploy-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: docker build and docker push
          command: |
            docker build -t $DOCKER_IMAGE:develop-$CIRCLE_SHA1 .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1

workflows:
  version: 2
  develop:
    jobs:
      - install:
          filters:
            branches:
              only: dev
      - test:
          filters:
            branches:
              only: dev
          requires:
            - install
      - build:
          filters:
            branches:
              only: dev
          requires:
            - test
      - deploy-test:
          filters:
            branches:
              only: dev
          requires:
            - build
  master:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
          requires:
            - install
      - build:
          filters:
            branches:
              only: master
          requires:
            - install
            - test
