name: Test pull request

on:
  pull_request

jobs:
  test-PR:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, test, and build
      run: |
        npm install
      env:
        CI: true
    - name: npm lint
      run: |
        npm run lint
        npm run lint:style
      env:
        CI: true
    - name: npm test
      run: |
        npm run test:unit
      env:
        CI: true
